# Generated by Django 5.1.7 on 2025-03-07 19:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("membership_paid", models.BooleanField(default=False)),
                ("membership_expiry_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Usuario Estándar", "Usuario Estándar"),
                            ("Usuario Premium", "Usuario Premium"),
                        ],
                        default="Usuario Estándar",
                        max_length=50,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Masculino", "Masculino"),
                            ("Femenino", "Femenino"),
                            ("Otro", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Soltero/a", "Soltero/a"),
                            ("Casado/a", "Casado/a"),
                            ("Divorciado/a", "Divorciado/a"),
                            ("Viudo/a", "Viudo/a"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Estudiante", "Estudiante"),
                            ("Profesional", "Profesional"),
                            ("Empleado", "Empleado"),
                            ("Empresario", "Empresario"),
                            ("Desempleado", "Desempleado"),
                            ("Otro", "Otro"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "cdunico",
                    models.CharField(
                        blank=True, editable=False, max_length=7, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartamento"),
                            ("house", "Casa"),
                            ("loft", "Loft"),
                            ("studio", "Estudio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("includes_admin", models.BooleanField(default=False)),
                (
                    "admin_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("number_of_occupants", models.PositiveIntegerField(default=1)),
                ("number_of_rooms", models.PositiveIntegerField(default=1)),
                ("number_of_bathrooms", models.PositiveIntegerField(default=1)),
                ("has_parking", models.BooleanField(default=False)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="apartments", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
                "db_table": "apartment",
            },
        ),
    ]
