# Generated by Django 2.2.28 on 2024-08-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='closet',
        ),
        migrations.AddField(
            model_name='service',
            name='closet',
            field=models.BooleanField(default=False),
        ),
    ]
