# Generated by Django 5.0.4 on 2024-06-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astraduser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='financial_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='membership_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Estudiante', 'Estudiante'), ('Profesional', 'Profesional'), ('Empleado', 'Empleado'), ('Empresario', 'Empresario'), ('Desempleado', 'Desempleado'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='astraduser',
            name='role',
            field=models.CharField(choices=[('Usuario Estándar', 'Usuario Estándar'), ('Usuario Premium', 'Usuario Premium')], default='Usuario Estándar', max_length=50),
        ),
    ]
