# Generated by Django 5.0.4 on 2024-07-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_account_board_patrimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimony',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
