# Generated by Django 5.0.3 on 2024-07-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_patrimony_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='patrimony',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.patrimony'),
        ),
    ]
